#!/usr/bin/env node

const execa = require('execa');

async function main() {
  const coreVersion = await require('./rapid-core/publish');
  const cliVersion = await require('./rapid-cli/publish');
  const templateVersion = await require('./rapid-template/publish');
  await execa('npm', ['install', '--global', `@simplej/rapid-cli@${cliVersion}`]);
}

main();
