#!/usr/bin/env node

const wait = ms => new Promise(resolve => setTimeout(resolve, ms));

async function main() {
  await require('./rapid-core/publish');
  await wait(3000);
  await require('./rapid-template/publish');
}

main();
